# Site settings
title: Sachoco's Dev Note
email: sachoco@gmail.com
description: Sachoco (Satoshi Shiraishi) is a web developer from the Flatland.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sachoco.github.io/" # the base hostname & protocol for your site
twitter_username: donachocolate
github_username:  sachoco

# Build settings
markdown: kramdown
